services:
  vk-bot:
    build:
      context: .
    image: vk-bot:latest
    env_file: .env
    ports:
      - "8788:8788"
      - "4173:4173"
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
